---
- name: Include encrypted proxmox access token from infrasctructure_secrect
  delegate_to: localhost
  ansible.builtin.include_vars: "../../../infrastructure_secrets/proxmox_user.yml"
  when: "lookup('env', 'CI_PIPELINE_SOURCE') != ''"
  no_log: true

- name: Add proxmox access token to required variables
  ansible.builtin.set_fact:
    proxmox_host: "{{ lookup('ansible.builtin.env', 'PROXMOX_HOST', default=proxmox_host) }}"
    proxmox_techuser: "{{ lookup('ansible.builtin.env', 'PROXMOX_USER', default=proxmox_tech_user_name_encrypted) }}"
    proxmox_techuser_token_id: "{{ lookup('ansible.builtin.env', 'PROXMOX_USER_TOKEN_ID', default=proxmox_tech_user_token_id_encrypted) }}"
    proxmox_techuser_token_secret: "{{ lookup('ansible.builtin.env', 'PROXMOX_USER_TOKEN_SECRET', default=proxmox_tech_user_token_secret_encrypted) }}"
  no_log: true

- name: Include encrypted proxmox vm credentials from infrasctructure_secrect
  delegate_to: localhost
  no_log: true
  ansible.builtin.include_vars:
    file: "{{ item }}"
  loop:
    - "../../../infrastructure_secrets/ansible_user.yml"
    - "../../../infrastructure_secrets/container_user.yml"
